<?php

/**
 * Recommendations template
 *
 * @category   ExtensionsStore
 * @package    ExtensionsStore_AutoCompleteRecommendations
 * @author     Extensions Store <admin@extensions-store.com>
 */

if ($this->getRecommendations()->getSize()):
    $_helper = $this->helper('catalog/output');
?>
<li class="autocompleterecommendations"><div class="recommendations-header"><?php echo $this->getHeaderLabel() ?></div>
    <ol class="recommendations">
<?php foreach ($this->getRecommendations() as $_product): ?>
        <li class="recommendation <?php echo $_product->getSku() ?>">
        	<div class="row">
	        	<div class="col-xs-3">
		            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="recommendation-image">
		                <?php $_imgSize = 50; ?>
		                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
		                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
		            </a>        	
	        	</div>
	        	<div class="col-xs-9">
		            <span><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></span>
	        	</div>        	
        	</div>
        </li>
<?php endforeach; ?>
    </ol>
</li>
<?php 
endif;
?>