<?php

/**
 * Recommendations template
 *
 * @category   ExtensionsStore
 * @package    ExtensionsStore_AutoCompleteRecommendations
 * @author     Extensions Store <admin@extensions-store.com>
 */

if ($this->getRecommendations()->getSize()):
    $_helper = $this->helper('catalog/output');
?>
<li><span><?php echo $this->getHeaderLabel() ?></span>
    <ol class="recommendations">
<?php foreach ($this->getRecommendations() as $_product): ?>
        <li class="recommendation <?php echo $_product->getSku() ?>">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="recommendation-image">
                <?php $_imgSize = 50; ?>
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>        
            <span><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></span>
        </li>
<?php endforeach; ?>
    </ol>
</li>
<?php 
endif;
?>