<?php

/**
 * Recommendations template
 *
 * @category   ExtensionsStore
 * @package    ExtensionsStore_AutoCompleteRecommendations
 * @author     Extensions Store <admin@extensions-store.com>
 */

if ($this->getRecommendations()->getSize()):
    $_helper = $this->helper('catalog/output');
?>
<li class="autocompleterecommendations"><div class="recommendations-header"><?php echo $this->getHeaderLabel() ?></div>
    <ol class="recommendations">
<?php foreach ($this->getRecommendations() as $_product): ?>
	<?php $title = ($this->getImageLabel($_product, 'small_image')) ? $this->getImageLabel($_product, 'small_image') : $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
        <li class="recommendation <?php echo $_product->getSku() ?>">
        	<div class="row">
		        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($title, null, true) ?>" class="recommendation-image">
		        	<div class="col-xs-3">
			                <?php $_imgSize = 50; ?>
			                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
			                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
		        	</div>
		        	<div class="col-xs-9">
			            <span><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
		        	</div>   
	        	</a>     	
        	</div>
        </li>
<?php endforeach; ?>
    </ol>
</li>
<?php 
endif;
?>